### ISSUE TITLE
Error in cadd2vcf.py: UnboundLocalError: local variable 'header' referenced before assignment

### ISSUE THREAD

**Issue by komalsrathi** [brentp/vcfanno#39]
I tried running `cadd2vcf.py` on `whole_genome_SNVs.tsv.compressed.gz` that comes with the gemini installation, but I am getting an error:

```
python cadd2vcf.py whole_genome_SNVs.tsv.compressed.gz | bgzip -c > cadd_v1.3.vcf.gz

Traceback (most recent call last):
  File "cadd2vcf.py", line 36, in <module>
    main(a.precision, a.path)
  File "cadd2vcf.py", line 20, in main
    d = dict(zip(header, line.rstrip().split("\t")))
UnboundLocalError: local variable 'header' referenced before assignment
```

P.S: I had to fix `print ` to `print(` as well.

**Comment by brentp** [comment]
ok. I'll update the print. I just used it on python 2. 
What do the first few linse of the original cadd file look like?

The script expects a '#Chrom' line to mark the header.

**Comment by komalsrathi** [comment]
The original tsv file has no header: 

```
1       10001   T       -0.53,-0.64,-0.64       1.60,1.17,1.19
1       10002   A       -0.64,-0.65,-0.53       1.17,1.15,1.57
1       10003   A       -0.64,-0.64,-0.53       1.19,1.17,1.60
1       10004   C       -0.83,-0.89,-0.77       0.61,0.46,0.77
1       10005   C       -0.83,-0.89,-0.77       0.61,0.46,0.77
1       10006   C       -0.83,-0.89,-0.77       0.61,0.46,0.77
```

**Comment by brentp** [comment]
What file are you using? You should get the one directly from the CADD site:
http://krishna.gs.washington.edu/download/CADD/v1.3/whole_genome_SNVs.tsv.gz

**Comment by brentp** [comment]
http://cadd.gs.washington.edu/download

**Comment by komalsrathi** [comment]
Oh got it. The names were so similar I thought thats the file to use.

**Comment by brentp** [comment]
I just pushed a change to make the print work on both python 2 and 3.

**Comment by komalsrathi** [comment]
I downloaded the file and this is how it looks:

```
## CADD v1.3 (c) University of Washington and Hudson-Alpha Institute for Biotechnology 2013-2015. All rights reserved.
#Chrom  Pos     Ref     Alt     RawScore        PHRED
1       10001   T       A       0.337036        6.046
1       10001   T       C       0.143254        4.073
1       10001   T       G       0.202491        4.705
1       10002   A       C       0.192576        4.601
1       10002   A       G       0.178363        4.450
1       10002   A       T       0.347401        6.143
```

when I use: 

```
python cadd2vcf.py whole_genome_SNVs.tsv.gz | bgzip -c > cadd_v1.3.vcf.gz

Traceback (most recent call last):
  File "cadd2vcf.py", line 36, in <module>
    main(a.precision, a.path)
  File "cadd2vcf.py", line 20, in main
    d = dict(zip(header, line.rstrip().split("\t")))
UnboundLocalError: local variable 'header' referenced before assignment
```

zcat cadd_v1.3.vcf.gz

```
##fileformat=VCFv4.1
##INFO=<ID=raw,Number=1,Type=Float,Description="raw cadd score">
##INFO=<ID=phred,Number=1,Type=Float,Description="phred-scaled cadd score">
##CADDCOMMENT=<ID=comment,comment="CADD v1.3 (c) University of Washington and Hudson-Alpha Institute for Biotechnology 2013-2015. All rights reserved.">
#CHROM  POS ID  REF ALT QUAL    FILTER INFO
```

**Comment by brentp** [comment]
There was a bug in the script as well. I just pushed now, again. If it doesn't work on python3, it will on python2.
